version: '3'
services:
  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - '80:80'
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./web:/var/www/html
  app:
    container_name: app
    image: ghcr.io/yoshitaka-motomura/socket-app:1.0.3
    environment:
      - APP_NAME=app
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_DB=0
      - TZ=Asia/Tokyo
      - LOG_LEVEL=info
  redis:
    container_name: redis
    image: redis:latest
    environment:
      - TZ=Asia/Tokyo
    volumes:
      - ./data/redis:/data
  # redisinsight:
  #   image: redislabs/redisinsight:latest
  #   ports:
  #     - '8001:8001'
  #   volumes:
  #     - ./data/redisinsight:/db
  #   depends_on:
  #     - redis
